[package]
name = "executor"
edition = "2024.beta"
license = "Apache 2.0"
authors = ["Wormhole Labs"]

[dependencies]

[addresses]
executor = "0x0"

[dev-dependencies]

[dev-addresses]
executor = "0x0"
