// Renders TypeScript SDK clients from enriched Codama IDL JSON files into a
// single publishable package at clients/js/. Each program gets its own
// subdirectory under src/generated/.
//
// Prerequisites: run `bun run generate:idl` first to produce the enriched IDLs.
// Usage: bun scripts/generate-sdk.mjs

import { createFromRoot } from "codama";
import { renderVisitor } from "@codama/renderers-js";
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, "..");
const packageDir = path.join(root, "clients", "js");

const programs = [
  { idl: "executor_quoter.json", output: "executorQuoter" },
  { idl: "executor_quoter_router.json", output: "executorQuoterRouter" },
];

for (const p of programs) {
  const idlPath = path.join(root, "idl", "codama", p.idl);
  const json = JSON.parse(readFileSync(idlPath, "utf-8"));
  const codama = createFromRoot(json);

  codama.accept(
    renderVisitor(packageDir, {
      deleteFolderBeforeRendering: true,
      formatCode: true,
      syncPackageJson: false,
      generatedFolder: path.join("src", "generated", p.output),
    }),
  );

  console.log(`Generated: ${p.output}`);
}

// Write root re-export index that exposes both programs.
const generatedDir = path.join(packageDir, "src", "generated");
mkdirSync(generatedDir, { recursive: true });

const indexContent = [
  "/**",
  " * This code was AUTOGENERATED using the Codama library.",
  " * Please DO NOT EDIT THIS FILE, instead rerun the generate script.",
  " *",
  " * @see https://github.com/codama-idl/codama",
  " */",
  "",
  ...programs.map((p) => `export * as ${p.output} from "./${p.output}";`),
  "",
].join("\n");

writeFileSync(path.join(generatedDir, "index.ts"), indexContent);
console.log("Generated: src/generated/index.ts");
