[project]
name = 'stacks'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'

[[project.requirements]]
contract_id = 'SP1E0XBN9T4B10E9QMR7XMFJPMA19D77WY3KP2QKC.self-listing-helper-v3'
[contracts.executor-state]
path = 'contracts/executor-state.clar'
clarity_version = 3
epoch = 'latest'

[contracts.executor]
path = 'contracts/executor.clar'
clarity_version = 3
epoch = '3.2'
depends_on = ['executor-state']
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
