name: aptos

on:
  pull_request:

jobs:
  test:
    name: Aptos Test
    runs-on: ubuntu-latest
    # https://github.com/aptos-labs/aptos-core/releases/tag/aptos-cli-v7.2.0
    # https://github.com/aptos-labs/aptos-core/commit/35102f5f33c69b8e48e030243a09edad80cbd946
    container: aptoslabs/tools:devnet_35102f5f33c69b8e48e030243a09edad80cbd946@sha256:06503b21b53ad904c7d689c47a78259b4891fa0d1c6932550c784bddc0d3cda0
    defaults:
      run:
        working-directory: aptos
    steps:
      - uses: actions/checkout@v4
      - run: sh ci.sh
