name: format
on: pull_request
permissions:
  contents: read
jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false
      - uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2
      - run: bun install --frozen-lockfile
      - run: bunx prettier --check .
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false
      # Pinned version of the v6 tag, which is a lightweight and hence mutable tag
      - uses: streetsidesoftware/cspell-action@214db1e3138f326d33b7a6a51c92852e89ab0618
        with:
          # For now, only lint markdown files
          files: "**/*.md"
          inline: warning
          # Only check files in the PR or push
          incremental_files_only: true
